### ISSUE TITLE
1.0.9040上似乎已经不支持了？

### ISSUE THREAD

**Issue by misaka10843** [aiqinxuancai/discord-proxy#17]
![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/69132853/5ba21ba0-6d6a-40f3-abb7-3a2012fbcc13)
在测试代理无问题，开启系统代理时可以进入，可能是dc更改了一些东西所以无法连接？

尝试了https://github.com/aiqinxuancai/DiscordProxyStart 以及单独将version.dll放进版本文件夹并且按要求配置还是不行
![image](https://github.com/aiqinxuancai/discord-proxy/assets/69132853/822c52af-da62-4536-8ce1-675ba47a7c0f)

**Comment by Blood3C** [comment]
+1  自从DC更新到1.0.9040就失效了，若dc安装在默认目录，启动后显示update failed - retrying in 10 seconds；若dc安装在自定义目录，启动后显示【没有找到discord安装目录】但我在配置文件里明确添加了dc路径
![屏幕截图(18)](https://github.com/aiqinxuancai/discord-proxy/assets/50765580/4b09dad7-4791-4ae3-9116-0460b868f1fe)
这个插件很方便快捷，之前用着一切正常，期待开发者大佬尽快更新！

**Comment by aiqinxuancai** [comment]
我本地目前是1.0.9042+windows10，使用[DiscordProxyStart](https://github.com/aiqinxuancai/DiscordProxyStart)或者添加参数的方式均可以正常启动。
你们系统都是windows11吗？

**Comment by Blood3C** [comment]
> 我本地目前是1.0.9042+windows10，使用[DiscordProxyStart](https://github.com/aiqinxuancai/DiscordProxyStart)或者添加参数的方式均可以正常启动。 你们系统都是windows11吗？

我是win10 今天dc又更新到1.0.9142了，我用的sing box默认端口20122，dc安装在自定义目录，通过[DiscordProxyStart](https://github.com/aiqinxuancai/DiscordProxyStart)启动还是一直检查更新进不去dc(version.dll自动复制过去了)，用系统代理可以正常进dc
![屏幕截图(20)](https://github.com/aiqinxuancai/discord-proxy/assets/50765580/9617bec8-4ba5-4e56-921b-f1ae13698ceb)
![屏幕截图(21)](https://github.com/aiqinxuancai/discord-proxy/assets/50765580/f0fe1280-b804-4620-af23-0623fe6f366d)

**Comment by aiqinxuancai** [comment]
> > 我本地目前是1.0.9042+windows10，使用[DiscordProxyStart](https://github.com/aiqinxuancai/DiscordProxyStart)或者添加参数的方式均可以正常启动。 你们系统都是windows11吗？
> 
> 我是win10 今天dc又更新到1.0.9142了，我用的sing box默认端口20122，dc安装在自定义目录，通过[DiscordProxyStart](https://github.com/aiqinxuancai/DiscordProxyStart)启动还是一直检查更新进不去dc(version.dll自动复制过去了)，用系统代理可以正常进dc ![屏幕截图(20)](https://private-user-images.githubusercontent.com/50765580/324716545-9617bec8-4ba5-4e56-921b-f1ae13698ceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTM4ODcsIm5iZiI6MTcxMzg1MzU4NywicGF0aCI6Ii81MDc2NTU4MC8zMjQ3MTY1NDUtOTYxN2JlYzgtNGJhNS00ZTU2LTkyMWItZjFhZTEzNjk4Y2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2MjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMzkzNWMxOWYzYjM2NjU1M2Q0ZDhkYjZjMWFmY2U3ODE5MDJlOWQ3ZTU4OTQ4NTJkYTZkZTljYjE1M2MwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3ub7mFnLTuN2g6s46ewgz5RZjxMU7AETwSqjYbeAE0) ![屏幕截图(21)](https://private-user-images.githubusercontent.com/50765580/324716575-f0fe1280-b804-4620-af23-0623fe6f366d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTM4ODcsIm5iZiI6MTcxMzg1MzU4NywicGF0aCI6Ii81MDc2NTU4MC8zMjQ3MTY1NzUtZjBmZTEyODAtYjgwNC00NjIwLWFmMjMtMDYyM2ZlNmYzNjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2MjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTFlZjRlYWZkN2ViOWMwODAyZGFhNjA4M2ZjMjcxMjA2NTZkMjNjYWU2ZjE4OGZjOThhYmQ1NzUxMTY1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dg6zYlPuZ6erFnN2onumpLHy_uU0dB518riN29PChWE)

我更新到了1.0.9142，确实这个版本无法加载version.dll

**Comment by aiqinxuancai** [comment]
发现1.0.9142的Discord.exe升级到了64位，我这边version.dll是32位的，两个项目现在都已经增加了对64位Discord.exe的支持，请测试一下看看吧。

**Comment by Blood3C** [comment]
> 发现1.0.9142的Discord.exe升级到了64位，我这边version.dll是32位的，两个项目现在都已经增加了对64位Discord.exe的支持，请测试一下看看吧。

开发者66666 更新得很及时，我试用可以正常启动了，好人一生平安~
