### ISSUE TITLE
无法找到函数GetFileVersionInfoExA，程序无法正常运行

### ISSUE THREAD

**Issue by HelloLoser** [aiqinxuancai/discord-proxy#2]
无法打开，提示报错
![image](https://user-images.githubusercontent.com/9430217/147308064-42cc31a1-017a-467f-a538-bc26bad23130.png)

**Comment by aiqinxuancai** [comment]
由于是在win10x64生成的劫持方法，缺少这个函数，0.0.8版本会修复掉
