### ISSUE TITLE
不知道为什么 有时候能正常进频道有时候卡在连接中

### ISSUE THREAD

**Issue by Aftertea123** [aiqinxuancai/discord-proxy#22]
每一次进频道似乎相当看运气  大部分时间会卡在连接中大概5到10分钟 有时候运气好就是一两分钟 是因为我使用的是v2ray的pac模式才会导致这个问题的吗 但是又只有pac模式可以全部让steam下载规则绕过core来达到下载满速

**Comment by Aftertea123** [comment]
修正一下问题 又研究了一下 现在不会出现卡连接中了 但是进频道还是看端口运气 以日本地区举例 10000以上的地址进入服务器一切正常 只要分配到10000以下 似乎都会出现丢包率奇高无比的问题
2024/08/20 13:55:50 127.0.0.1:49985 accepted //japan11031.discord.media:443 [http -> proxy]
2024/08/20 13:56:14 127.0.0.1:49988 accepted //japan11120.discord.media:443 [http -> proxy]
2024/08/20 13:56:31 127.0.0.1:49991 accepted //japan6885.discord.media:443 [http -> proxy]
2024/08/20 13:56:45 127.0.0.1:49993 accepted //japan7678.discord.media:443 [http -> proxy]
2024/08/20 13:56:51 127.0.0.1:49995 accepted //japan1661.discord.media:443 [http -> proxy]
2024/08/20 13:57:08 127.0.0.1:49997 accepted //japan11015.discord.media:443 [http -> proxy]

**Comment by aiqinxuancai** [comment]
从实现上来说，并不会导致连接质量摇摆不定，即只有生效和无效两种状态，我觉得你的问题可能和代理有一定关系。

**Comment by Aftertea123** [comment]
好的 我又调整了一下pac模式的规则 应该就是代理规则漏了的缘故 感谢答复
