### ISSUE TITLE
Discord更新1.0.9004版后失效，已重放dll

### ISSUE THREAD

**Issue by Snoolee** [aiqinxuancai/discord-proxy#4]
感谢分享。
之前一直正常使用，今天启动Discord更新1.0.9004后方法失效，已重新放置dll到04目录且添加启动参数。

![20220218091930](https://user-images.githubusercontent.com/52028866/154599186-cf65c522-d1b1-4fb7-a68b-7edd3a886435.jpg)

**Comment by aiqinxuancai** [comment]
![image](https://user-images.githubusercontent.com/4475018/154608482-e2a9a809-1fe1-4ee5-b019-f20cd95a116f.png)
我这里测试正常，version.dll也正常被加载

**Comment by Snoolee** [comment]
不好意思，确实可用。
找到原因了，新建的快捷方式里，后缀参数我直接复制了你repo首页上的1081，而之前我一直用默认的1080，改过来就正常了。
再次感谢你的分享和维护。
