### ISSUE TITLE
Discord 自动更新到版本1.0.9004，然后处于Starting 进入不了

### ISSUE THREAD

**Issue by hang-wang-sys** [aiqinxuancai/discord-proxy#5]
win10, 使用该教程1.0.9003能够登录。现在Discord 自动更新到版本1.0.9004，然后处于Starting 进入不了，卸载重装也不行也处于STARTING...，请问如何解决，谢谢

**Comment by aiqinxuancai** [comment]
重新把version.dll放在1.0.9004所在的目录中即可

**Comment by hang-wang-sys** [comment]
> 重新把version.dll放在1.0.9004所在的目录中即可，因为更新应用版本是直接换掉整个目录，你之前放在1.0.9003的那个version.dll被一起删掉了

不行的话，还有其他原因么，version是重新放过的。

**Comment by aiqinxuancai** [comment]
> > 重新把version.dll放在1.0.9004所在的目录中即可，因为更新应用版本是直接换掉整个目录，你之前放在1.0.9003的那个version.dll被一起删掉了
> 
> 不行的话，还有其他原因么，version是重新放过的。

没有其他原因，从头检查快捷方式的的代理地址对不对吧，我这里今早测过没有任何问题。

**Comment by hang-wang-sys** [comment]
> > > 重新把version.dll放在1.0.9004所在的目录中即可，因为更新应用版本是直接换掉整个目录，你之前放在1.0.9003的那个version.dll被一起删掉了
> > 
> > 
> > 不行的话，还有其他原因么，version是重新放过的。
> 
> 没有其他原因，从头检查快捷方式的的代理地址对不对吧，我这里今早测过没有任何问题。

好的 解决了，我这里需要把%appdata%文件下的discord删除掉，感谢

**Comment by Paladinhanxiao** [comment]
> 

遇到了同样的问题，check update时走了代理，然后就是一直start（可能没走代理）。 把%appdata%文件下的discord删除掉也没有用。

**Comment by chux0519** [comment]
> > 
> 
> 遇到了同样的问题，check update时走了代理，然后就是一直start（可能没走代理）。 把%appdata%文件下的discord删除掉也没有用。 代理用的v2rayN. 系统版本是win10 21H2

遇到同样的问题，前几天 windows 会提示有不必要的程序控制 blablabla 但是功能正常，但今天打不开了，一直 update 那里失败，看起来没有走代理

**Comment by chux0519** [comment]
> > > 
> > 
> > 
> > 遇到了同样的问题，check update时走了代理，然后就是一直start（可能没走代理）。 把%appdata%文件下的discord删除掉也没有用。 代理用的v2rayN. 系统版本是win10 21H2
> 
> 遇到同样的问题，前几天 windows 会提示有不必要的程序控制 blablabla 但是功能正常，但今天打不开了，一直 update 那里失败，看起来没有走代理

不知道是什么问题，重启重装 discord，重放 dll 解决了。怀疑是加速器或是 clash 之类导致的问题

**Comment by SettingDust** [comment]
报错 `app\app-1.0.9006\Discord.exe: invalid option -- `-p'`，卡 Starting，看日志是代理在哪里失败了，然后连不到 discord 了。更新没问题
