### ISSUE TITLE
似乎是不能使用socks5的方式进行代理

### ISSUE THREAD

**Issue by ArtHuge** [aiqinxuancai/discord-proxy#6]

**Comment by WhitLor** [comment]
好像是，加 --a=--proxy-server=socks5://127.0.0.1:2013没有生效，我做这个工具要么ss5，要么全局才有http，没有单独的http，难受，但不想全局

**Comment by aiqinxuancai** [comment]
建议使用https://github.com/ginuerzh/gost项目，将socks代理转为http代理。

**Comment by prajna0** [comment]
如果用的是Clash for Windows，直接设置为` --a=--proxy-server=http://127.0.0.1:7890`就好了，CFW是混合代理，HTTP+SOCKS5

目前用完作者的dll，很舒服

**Comment by jingslunt** [comment]
Update.exe --processStart Discord.exe --a=--proxy-server=socks5://127.0.0.1:10808

**Comment by hdrover** [comment]
There is such a project. It works similarly but supports socks5.
有这样一个项目。它的工作方式类似，但支持socks5。
https://github.com/hdrover/discord-drover
