### ISSUE TITLE
对于 app-1.0.9005 无效

### ISSUE THREAD

**Issue by JackuXL** [aiqinxuancai/discord-proxy#7]
如题，app-1.0.9005 不存在 version.dll 文件，直接放入文件夹后启动无效
环境：Windows 11 + Discord app-1.0.9005 + Clash for Windows v0.19.25

![Snipaste_2022-07-28_18-29-19](https://user-images.githubusercontent.com/58510349/181484506-0d311be2-4dbb-4749-8945-7ce75fe598aa.png)
![Snipaste_2022-07-28_18-29-24](https://user-images.githubusercontent.com/58510349/181484508-9e442e2f-5e1f-473a-b5b3-fe2735f71203.png)
![Snipaste_2022-07-28_18-28-38](https://user-images.githubusercontent.com/58510349/181484493-c313575b-7168-407d-9f55-c93232f794f1.png)
![Snipaste_2022-07-28_18-28-44](https://user-images.githubusercontent.com/58510349/181484504-e3ea27a4-dbb4-4731-833b-6826f1400618.png)

**Comment by hechaog** [comment]
可以用 启动的时间比较长

**Comment by Inori** [comment]
不是不存在version.dll，version.dll也能加载
而且update的过程中代理设置也是生效的。
不过现在貌似还有其它地方也需要通过代理链接，不然会卡在Starting

**Comment by Inori** [comment]
https://github.com/aiqinxuancai/discord-proxy/pull/8

**Comment by aiqinxuancai** [comment]
经过在Windows11的测试，我目前无法复现这个问题，如果有更多线索欢迎提供
![GIF 2022-8-13 11-00-59](https://user-images.githubusercontent.com/4475018/184466005-8edb13ed-01ed-469f-9926-c5e43f5fd120.gif)

**Comment by aiqinxuancai** [comment]
> 如题，app-1.0.9005 不存在 version.dll 文件，直接放入文件夹后启动无效 环境：Windows 11 + Discord app-1.0.9005 + Clash for Windows v0.19.25
> 
> ![Snipaste_2022-07-28_18-29-19](https://user-images.githubusercontent.com/58510349/181484506-0d311be2-4dbb-4749-8945-7ce75fe598aa.png) ![Snipaste_2022-07-28_18-29-24](https://user-images.githubusercontent.com/58510349/181484508-9e442e2f-5e1f-473a-b5b3-fe2735f71203.png) ![Snipaste_2022-07-28_18-28-38](https://user-images.githubusercontent.com/58510349/181484493-c313575b-7168-407d-9f55-c93232f794f1.png) ![Snipaste_2022-07-28_18-28-44](https://user-images.githubusercontent.com/58510349/181484504-e3ea27a4-dbb4-4731-833b-6826f1400618.png)

请注意，readme中描述的是针对桌面快捷方式添加--a=参数，而桌面快捷方式链接的是**Update.exe**文件，从图片中可见你的快捷方式是针对Discord.exe，这样会让你每次版本更新都要去重新创建快捷方式，建议不要。

如果实在是要从Discord.exe启动，则可以将“--a=”去掉后传递给Discord.exe。

**Comment by aiqinxuancai** [comment]
![image](https://user-images.githubusercontent.com/4475018/184467288-3329b764-cb75-4e85-a1c5-9216e7d4c3c2.png)
请检查你的discord的clash流量是否通过代理

**Comment by Inori** [comment]
不加我那个PR的情况下，只有updates.discord.com走代理，所以升级正常。但是会卡在starting。
版本是1.0.9005，系统Win10

**Comment by aiqinxuancai** [comment]
> 不加我那个PR的情况下，只有updates.discord.com走代理，所以升级正常。但是会卡在starting。 版本是1.0.9005，系统Win10

readme上面所说的桌面快捷方式为安装时自动创建的快捷方式，目标指向是Update.exe，而非自行从Discord.exe所创建的，修改完毕后的完整命令行样例：
```
C:\Users\xxxxxx\AppData\Local\Discord\Update.exe --processStart Discord.exe --a=--proxy-server=http://127.0.0.1:1081
```
